# systems/alerts.py

from dataclasses import dataclass
import config

@dataclass
class Alert:
    timestamp: float
    sensor_id: int
    x: float
    y: float
    region: str
    severity: str
    temperature: float
    humidity: float
    smoke: float


class AlertManager:

    def __init__(self):
        '''
        Initialize the AlertManager to handle alert creation and tracking.
        '''
        self.active_alerts = []
        self.alert_history = []
        self.last_tick_alerts = []

    def begin_tick(self):
        '''
        Prepare the system for new tick by clearing last tick's alerts.
        '''
        self.last_tick_alerts = []

    def _expire_old_alerts(self, current_time):
        '''
        Remove expired active alerts based on their timestamp and configured TTL.
        INPUT: 
            - current_time: float, current simulation time.
        '''

        # REMOVE EXPIRED ACTIVE ALERTS
        ttl = config.ALERT_TTL
        self.active_alerts = [
            alert
            for alert in self.active_alerts
            if (current_time - alert.timestamp) <= ttl
        ]

    def create_alert(self, processed_event):
        '''
        Create an Alert object from a processed detection event.
        INPUT: 
            - processed_event: dict, detection result generated by a worker.
        OUTPUT: 
            - Alert, newly created Alert object.
        '''
        
        # 1 BUILD ALERT OBJECT FROM DETECTION EVENT
        alert = Alert(
            timestamp=processed_event["timestamp"],
            sensor_id=processed_event["sensor_id"],
            x=processed_event["x"],
            y=processed_event["y"],
            region=processed_event["region"],
            severity=processed_event["severity"],
            temperature=processed_event["temperature"],
            humidity=processed_event["humidity"],
            smoke=processed_event["smoke"]
        )

        # 2: ADD ALERT TO ACTIVE, HISTORICAL, AND CURRENT-TICK TRACKING
        self.active_alerts.append(alert)
        self.alert_history.append(alert)
        self.last_tick_alerts.append(alert)
        
        return alert

    def ingest_processed_events(self, processed_by_region):
        '''
        Create alerts from processed worker events.
        INPUT: 
            - processed_by_region: dict, processed events grouped by region.
        OUTPUT: 
            - created: [Alert], alerts created during this tick.
        '''
        
        created = []

        # 1: SCAN ALL REGIONAL DETECTION RESULTS
        for region_events in processed_by_region.values():
            
            # 1.1: CREATE ALERTS FOR DETECTED EVENTS
            for event in region_events:
                if event["detected"]:
                    created.append(self.create_alert(event))

        return created

    def get_last_tick_count(self):
        '''
        Return int number of alerts created during the most recent tick.
        '''
        return len(self.last_tick_alerts)

    def get_total_alert_count(self):
        '''
        Return int for total number of alerts generated since the system started.
        '''
        return len(self.alert_history)

    def get_active_alert_count(self):
        '''
        Return the number of currently active alerts that have not yet expired.
        '''
        return len(self.active_alerts)

    def get_last_tick_summary(self):
        '''
        Summarize alerts by severity for the current tick.
        OUTPUT: 
            - dict, counts of low/medium/high severity alerts created this tick.
        '''

        summary = {"low": 0, "medium": 0, "high": 0}

        # COUNT ALERTS IN EACH SEVERITY CATEGORY
        for alert in self.last_tick_alerts:
            if alert.severity in summary:
                summary[alert.severity] += 1

        return summary

    def get_recent_alerts(self, limit=10):
        '''
        Return most recent alerts.
        INPUT: 
            - limit: int, maximum number of recent alerts to return.
        OUTPUT: 
            - [Alert], most recent alerts up to the specified limit.
        '''
        return self.alert_history[-limit:]

    def reset(self):
        '''
        Reset alert system state.
        '''
        self.active_alerts = []
        self.alert_history = []
        self.last_tick_alerts = []
